# Generated by Django 5.1.1 on 2024-10-08 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.file')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composition_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Testing'), (1, 'Finalized')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ae_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_templates', to='video.aeversion')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_templates', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.file')),
                ('fonts', models.ManyToManyField(blank=True, related_name='video_templates', to='video.font')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_templates', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StaticLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('layer_type', models.IntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Audio')])),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.file')),
                ('video_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_layers', to='video.videotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('layer_type', models.IntegerField(choices=[(0, 'Data'), (1, 'Image'), (2, 'Video'), (3, 'Audio')])),
                ('helper_text', models.TextField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.file')),
                ('video_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_layers', to='video.videotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='VideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.IntegerField(choices=[(0, 'Queued'), (1, 'Rendering'), (2, 'Uploading'), (3, 'Success'), (4, 'Failed')], default=0)),
                ('job_id', models.CharField(max_length=255)),
                ('finished_job_details', models.JSONField(blank=True, null=True)),
                ('video_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_variants', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.file')),
                ('video_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_variants', to='video.videotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='VideoVariantLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('layer_type', models.IntegerField(choices=[(0, 'Data'), (1, 'Image'), (2, 'Video'), (3, 'Audio')])),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.file')),
                ('video_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='video.videovariant')),
            ],
        ),
    ]
