# Generated by Django 5.1.1 on 2024-10-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplate',
            name='sample_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_videos', to='video.file'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='ae_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.aeversion'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='video.file'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='fonts',
            field=models.ManyToManyField(blank=True, to='video.font'),
        ),
    ]
