# Generated by Django 5.1.1 on 2024-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videotemplate_sample_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovariant',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
