# Generated by Django 5.1.1 on 2024-10-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videovariant_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videovariant',
            name='video_minutes',
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='video_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
