# Generated by Django 5.1.1 on 2024-10-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
