# Generated by Django 5.1.1 on 2024-10-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organizationmember_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'verbose_name_plural': 'Creditses'},
        ),
    ]
