# Generated by Django 5.1.1 on 2024-10-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_credits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
